### ISSUE TITLE
Unable to run JicamaJS

### ISSUE THREAD

**Issue by Squiggle** [jicamajs/jicamajs#1]
Hey - I've forked the repo, but I can't seem to get JicamaJS to run.

Can you update the docs to advise what I'm meant to do here?

**Comment by nickiannone** [comment]
I think you're supposed to invoke `jicama` and just use it in the global scope, like underscore/lodash. What bothers me is that there is no documentation for using this with various module/import systems.

**Comment by Squiggle** [comment]
I'll get right on that. Docs and unit tests comin' up!

**Comment by FailsafeNY** [comment]
Travis CI reports no issues, works on my computer.
